---
title: "IEProject"
output: pdf_document
date: "2024-04-17"
---

```{r}
library(dplyr)
df <- read.csv("data/data_weights.csv")
```

Converting Dtypes
```{r ,echo = False}
df$SEX <- factor(df$SEX)
df$RACE <- factor(df$RACE)
df$DEGFIELD <- factor(df$DEGFIELD)
df$PWSTATE2 <- factor(df$PWSTATE2)
summary(df)
```

Visualizations
```{r}
hist(df$INCTOT)
hist(I(log(df$INCTOT)))
```



```{r}
# Clustering Degree Field
df <- df %>%
  mutate(DEGFIELD_cluster = case_when(
    DEGFIELD %in% c(21, 24, 25, 36, 37, 51, 50) ~ "STEM",
    DEGFIELD %in% c(61) ~ "Health Sciences",
    DEGFIELD %in% c(11, 62, 56, 57, 59, 22) ~ "Business and Industry",
    DEGFIELD %in% c(15, 55, 33, 34, 64, 48, 49, 52, 54) ~ "Social Sciences and Humanities",
    DEGFIELD %in% c(23, 35) ~ "Education and Teaching",
    DEGFIELD %in% c(14, 60) ~ "Arts and Design",
    DEGFIELD %in% c(32, 53) ~ "Legal and Criminal Studies",
    DEGFIELD %in% c(13, 41) ~ "Science and Environmental Studies",
    DEGFIELD %in% c(40) ~ "Interdisciplinary Studies",
    DEGFIELD %in% c(19, 20) ~ "Communication and Media",
    DEGFIELD %in% c(58, 38) ~ "Technical and Vocational",
    DEGFIELD %in% c(26) ~ "Linguistics and Foreign Languages",
    DEGFIELD %in% c(29) ~ "Family and Consumer Studies",
  ))
```

```{r}
# Clustering Place of Work - State
df <- df %>%
  mutate(PWSTATE2_cluster = case_when(
    PWSTATE2 %in% c(09, 23, 33, 50, 25, 44, 36, 34, 42, 10, 24) ~ "Northeast Region",
    PWSTATE2 %in% c(39, 18, 17, 26, 55, 27, 19, 29, 38, 46, 31, 20) ~ "Midwest Region",
    PWSTATE2 %in% c(54, 51, 21, 47, 37, 45, 13, 01, 28, 05, 22, 12, 48, 40) ~ "South Region",
    PWSTATE2 %in% c(16, 30, 56, 32, 49, 08, 04, 35, 02, 53, 41, 06, 15) ~ "West Region",
    PWSTATE2 %in% c(11, 72, 73, 74) ~ "Other U.S. Territories and Special Areas",
    PWSTATE2 %in% c(80, 81, 82, 83, 84, 85, 86, 87, 88) ~ "International",
  ))
```

```{r}
df$DEGFIELD_cluster <- as.factor(df$DEGFIELD_cluster)
df$PWSTATE2_cluster <- as.factor(df$PWSTATE2_cluster)
```

```{r}
summary(df)
```

```{r}
df <- df %>%
  mutate(
    log_INCTOT = log(INCTOT),
    AGE_sq = AGE^2
  )

# Initialize a list to store models
models <- list()

# Loop over each level of PWSTATE2_cluster and fit a model
clusters <- unique(df$PWSTATE2_cluster)

for(cluster in clusters) {
  # Subset the data for the specific cluster
  subset_data <- df %>% filter(PWSTATE2_cluster == cluster)
  
  # Fit the linear model to the subset
  model <- lm(log_INCTOT ~ AGE + AGE_sq + SEX + RACE + UHRSWORK + DEGFIELD, data = subset_data)
  
  # Store the model in the list using the cluster name
  models[[cluster]] <- model
}
```